# Response Pipeline Service Configuration

server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: response-pipeline-service
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 1
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Logging Configuration
logging:
  level:
    com.agenticsearch.responsepipeline: INFO
    org.springframework.web.reactive: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: true

---
# Development Profile
spring:
  config:
    activate:
      on-profile: development

logging:
  level:
    com.agenticsearch.responsepipeline: DEBUG
    org.springframework.web.reactive: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: production

logging:
  level:
    com.agenticsearch.responsepipeline: INFO
    org.springframework.web.reactive: WARN

# Production-specific configurations
server:
  compression:
    enabled: true
  http2:
    enabled: true

