server:
  port: 8082

spring:
  application:
    name: vector-search
  redis:
    host: localhost
    port: 6379

vertex-ai:
  project-id: future-of-search
  location: us-central1
  kill-switch: false
  daily-budget: 8
